import { Celebrity } from './types';

// Fallback data for popular celebrities when AI gateway is unavailable
export const fallbackCelebrities: Record<string, Celebrity> = {
  'michael jordan': {
    id: 'michael-jordan',
    name: 'Michael Jordan',
    profession: 'Former NBA Player & Businessman',
    netWorth: 3500000000,
    annualEarnings: 260000000,
    category: 'athletes',
    funFacts: ['Michael Jordan makes more from Nike royalties today than he ever did playing basketball.'],
  },
  'taylor swift': {
    id: 'taylor-swift',
    name: 'Taylor Swift',
    profession: 'Singer-Songwriter',
    netWorth: 1100000000,
    annualEarnings: 185000000,
    category: 'musicians',
    funFacts: ['The Eras Tour became the highest-grossing concert tour of all time.'],
  },
  'elon musk': {
    id: 'elon-musk',
    name: 'Elon Musk',
    profession: 'CEO of Tesla & SpaceX',
    netWorth: 250000000000,
    annualEarnings: 25000000000,
    category: 'tech-billionaires',
    funFacts: ['Elon Musk earns more per hour than most people earn in a lifetime.'],
  },
  'lebron james': {
    id: 'lebron-james',
    name: 'LeBron James',
    profession: 'NBA Player',
    netWorth: 1200000000,
    annualEarnings: 128000000,
    category: 'athletes',
    funFacts: ['LeBron is the first active NBA player to become a billionaire.'],
  },
  'beyoncé': {
    id: 'beyonce',
    name: 'Beyoncé',
    profession: 'Singer & Businesswoman',
    netWorth: 800000000,
    annualEarnings: 120000000,
    category: 'musicians',
    funFacts: ['Beyoncé has won more Grammys than any other artist in history.'],
  },
  'beyonce': {
    id: 'beyonce',
    name: 'Beyoncé',
    profession: 'Singer & Businesswoman',
    netWorth: 800000000,
    annualEarnings: 120000000,
    category: 'musicians',
    funFacts: ['Beyoncé has won more Grammys than any other artist in history.'],
  },
  'oprah': {
    id: 'oprah-winfrey',
    name: 'Oprah Winfrey',
    profession: 'Media Executive & Philanthropist',
    netWorth: 2700000000,
    annualEarnings: 275000000,
    category: 'hollywood',
    funFacts: ['Oprah was the first Black female billionaire in American history.'],
  },
  'oprah winfrey': {
    id: 'oprah-winfrey',
    name: 'Oprah Winfrey',
    profession: 'Media Executive & Philanthropist',
    netWorth: 2700000000,
    annualEarnings: 275000000,
    category: 'hollywood',
    funFacts: ['Oprah was the first Black female billionaire in American history.'],
  },
  'cristiano ronaldo': {
    id: 'cristiano-ronaldo',
    name: 'Cristiano Ronaldo',
    profession: 'Professional Footballer',
    netWorth: 600000000,
    annualEarnings: 200000000,
    category: 'athletes',
    funFacts: ['Ronaldo is the most-followed person on Instagram with over 600 million followers.'],
  },
  'kim kardashian': {
    id: 'kim-kardashian',
    name: 'Kim Kardashian',
    profession: 'Media Personality & Businesswoman',
    netWorth: 1700000000,
    annualEarnings: 150000000,
    category: 'influencers',
    funFacts: ['Kim can earn over $1 million for a single Instagram post.'],
  },
  'dwayne johnson': {
    id: 'dwayne-johnson',
    name: 'Dwayne "The Rock" Johnson',
    profession: 'Actor & Producer',
    netWorth: 800000000,
    annualEarnings: 125000000,
    category: 'hollywood',
    funFacts: ['The Rock was once the highest-paid actor in Hollywood history.'],
  },
  'the rock': {
    id: 'dwayne-johnson',
    name: 'Dwayne "The Rock" Johnson',
    profession: 'Actor & Producer',
    netWorth: 800000000,
    annualEarnings: 125000000,
    category: 'hollywood',
    funFacts: ['The Rock was once the highest-paid actor in Hollywood history.'],
  },
  'jeff bezos': {
    id: 'jeff-bezos',
    name: 'Jeff Bezos',
    profession: 'Founder of Amazon',
    netWorth: 200000000000,
    annualEarnings: 20000000000,
    category: 'tech-billionaires',
    funFacts: ['Jeff Bezos makes the average US salary every 11 seconds.'],
  },
  'lionel messi': {
    id: 'lionel-messi',
    name: 'Lionel Messi',
    profession: 'Professional Footballer',
    netWorth: 650000000,
    annualEarnings: 130000000,
    category: 'athletes',
    funFacts: ['Messi has won more Ballon d\'Or awards than any other player in history.'],
  },
  'rihanna': {
    id: 'rihanna',
    name: 'Rihanna',
    profession: 'Singer & Businesswoman',
    netWorth: 1400000000,
    annualEarnings: 150000000,
    category: 'musicians',
    funFacts: ['Rihanna became a billionaire primarily through her Fenty Beauty business, not music.'],
  },
  'mark zuckerberg': {
    id: 'mark-zuckerberg',
    name: 'Mark Zuckerberg',
    profession: 'CEO of Meta',
    netWorth: 180000000000,
    annualEarnings: 18000000000,
    category: 'tech-billionaires',
    funFacts: ['Zuckerberg built Facebook in his Harvard dorm room at age 19.'],
  },
  'drake': {
    id: 'drake',
    name: 'Drake',
    profession: 'Rapper & Producer',
    netWorth: 260000000,
    annualEarnings: 95000000,
    category: 'musicians',
    funFacts: ['Drake is the most-streamed artist of all time on Spotify.'],
  },
  'kanye west': {
    id: 'kanye-west',
    name: 'Kanye West',
    profession: 'Rapper & Fashion Designer',
    netWorth: 400000000,
    annualEarnings: 100000000,
    category: 'musicians',
    funFacts: ['Kanye\'s Yeezy brand was once valued at over $1 billion.'],
  },
  'bill gates': {
    id: 'bill-gates',
    name: 'Bill Gates',
    profession: 'Co-founder of Microsoft',
    netWorth: 130000000000,
    annualEarnings: 13000000000,
    category: 'tech-billionaires',
    funFacts: ['Bill Gates has donated over $50 billion to charity through the Gates Foundation.'],
  },
  'tom brady': {
    id: 'tom-brady',
    name: 'Tom Brady',
    profession: 'Former NFL Quarterback',
    netWorth: 300000000,
    annualEarnings: 75000000,
    category: 'athletes',
    funFacts: ['Tom Brady has won more Super Bowls than any player in NFL history.'],
  },
};

export function getFallbackCelebrity(name: string): Celebrity | null {
  const normalizedName = name.toLowerCase().trim();
  return fallbackCelebrities[normalizedName] || null;
}
