project_id = "gzhrgnoowzhifpbnnevp"

[functions.admin-get-users]
verify_jwt = false

[functions.get-celebrity-data]
verify_jwt = false

[functions.increment-search]
verify_jwt = false

[functions.beta-invite]
verify_jwt = false

[functions.beta-feedback]
verify_jwt = false

[functions.admin-get-beta-data]
verify_jwt = false